---
apiVersion: v1
data:
  squid.conf: IwojIFJlY29tbWVuZGVkIG1pbmltdW0gY29uZmlndXJhdGlvbjoKIwoKIyBFeGFtcGxlIHJ1bGUgYWxsb3dpbmcgYWNjZXNzIGZyb20geW91ciBsb2NhbCBuZXR3b3Jrcy4KIyBBZGFwdCB0byBsaXN0IHlvdXIgKGludGVybmFsKSBJUCBuZXR3b3JrcyBmcm9tIHdoZXJlIGJyb3dzaW5nCiMgc2hvdWxkIGJlIGFsbG93ZWQKYWNsIGxvY2FsbmV0IHNyYyAwLjAuMC4xLTAuMjU1LjI1NS4yNTUJIyBSRkMgMTEyMiAidGhpcyIgbmV0d29yayAoTEFOKQphY2wgbG9jYWxuZXQgc3JjIDEwLjAuMC4wLzgJCSMgUkZDIDE5MTggbG9jYWwgcHJpdmF0ZSBuZXR3b3JrIChMQU4pCmFjbCBsb2NhbG5ldCBzcmMgMTAwLjY0LjAuMC8xMAkJIyBSRkMgNjU5OCBzaGFyZWQgYWRkcmVzcyBzcGFjZSAoQ0dOKQphY2wgbG9jYWxuZXQgc3JjIDE2OS4yNTQuMC4wLzE2IAkjIFJGQyAzOTI3IGxpbmstbG9jYWwgKGRpcmVjdGx5IHBsdWdnZWQpIG1hY2hpbmVzCmFjbCBsb2NhbG5ldCBzcmMgMTcyLjE2LjAuMC8xMgkJIyBSRkMgMTkxOCBsb2NhbCBwcml2YXRlIG5ldHdvcmsgKExBTikKYWNsIGxvY2FsbmV0IHNyYyAxOTIuMTY4LjAuMC8xNgkJIyBSRkMgMTkxOCBsb2NhbCBwcml2YXRlIG5ldHdvcmsgKExBTikKYWNsIGxvY2FsbmV0IHNyYyBmYzAwOjovNyAgICAgICAJIyBSRkMgNDE5MyBsb2NhbCBwcml2YXRlIG5ldHdvcmsgcmFuZ2UKYWNsIGxvY2FsbmV0IHNyYyBmZTgwOjovMTAgICAgICAJIyBSRkMgNDI5MSBsaW5rLWxvY2FsIChkaXJlY3RseSBwbHVnZ2VkKSBtYWNoaW5lcwoKYWNsIFNTTF9wb3J0cyBwb3J0IDQ0MwphY2wgU2FmZV9wb3J0cyBwb3J0IDgwCQkjIGh0dHAKYWNsIFNhZmVfcG9ydHMgcG9ydCAyMQkJIyBmdHAKYWNsIFNhZmVfcG9ydHMgcG9ydCA0NDMJCSMgaHR0cHMKYWNsIFNhZmVfcG9ydHMgcG9ydCA3MAkJIyBnb3BoZXIKYWNsIFNhZmVfcG9ydHMgcG9ydCAyMTAJCSMgd2FpcwphY2wgU2FmZV9wb3J0cyBwb3J0IDEwMjUtNjU1MzUJIyB1bnJlZ2lzdGVyZWQgcG9ydHMKYWNsIFNhZmVfcG9ydHMgcG9ydCAyODAJCSMgaHR0cC1tZ210CmFjbCBTYWZlX3BvcnRzIHBvcnQgNDg4CQkjIGdzcy1odHRwCmFjbCBTYWZlX3BvcnRzIHBvcnQgNTkxCQkjIGZpbGVtYWtlcgphY2wgU2FmZV9wb3J0cyBwb3J0IDc3NwkJIyBtdWx0aWxpbmcgaHR0cAphY2wgQ09OTkVDVCBtZXRob2QgQ09OTkVDVAoKIwojIFJlY29tbWVuZGVkIG1pbmltdW0gQWNjZXNzIFBlcm1pc3Npb24gY29uZmlndXJhdGlvbjoKIwojIERlbnkgcmVxdWVzdHMgdG8gY2VydGFpbiB1bnNhZmUgcG9ydHMKaHR0cF9hY2Nlc3MgZGVueSAhU2FmZV9wb3J0cwoKIyBEZW55IENPTk5FQ1QgdG8gb3RoZXIgdGhhbiBzZWN1cmUgU1NMIHBvcnRzCmh0dHBfYWNjZXNzIGRlbnkgQ09OTkVDVCAhU1NMX3BvcnRzCgojIE9ubHkgYWxsb3cgY2FjaGVtZ3IgYWNjZXNzIGZyb20gbG9jYWxob3N0Cmh0dHBfYWNjZXNzIGFsbG93IGxvY2FsaG9zdCBtYW5hZ2VyCmh0dHBfYWNjZXNzIGRlbnkgbWFuYWdlcgoKIyBXZSBzdHJvbmdseSByZWNvbW1lbmQgdGhlIGZvbGxvd2luZyBiZSB1bmNvbW1lbnRlZCB0byBwcm90ZWN0IGlubm9jZW50CiMgd2ViIGFwcGxpY2F0aW9ucyBydW5uaW5nIG9uIHRoZSBwcm94eSBzZXJ2ZXIgd2hvIHRoaW5rIHRoZSBvbmx5CiMgb25lIHdobyBjYW4gYWNjZXNzIHNlcnZpY2VzIG9uICJsb2NhbGhvc3QiIGlzIGEgbG9jYWwgdXNlcgojaHR0cF9hY2Nlc3MgZGVueSB0b19sb2NhbGhvc3QKCiMKIyBJTlNFUlQgWU9VUiBPV04gUlVMRShTKSBIRVJFIFRPIEFMTE9XIEFDQ0VTUyBGUk9NIFlPVVIgQ0xJRU5UUwojCgojIEV4YW1wbGUgcnVsZSBhbGxvd2luZyBhY2Nlc3MgZnJvbSB5b3VyIGxvY2FsIG5ldHdvcmtzLgojIEFkYXB0IGxvY2FsbmV0IGluIHRoZSBBQ0wgc2VjdGlvbiB0byBsaXN0IHlvdXIgKGludGVybmFsKSBJUCBuZXR3b3JrcwojIGZyb20gd2hlcmUgYnJvd3Npbmcgc2hvdWxkIGJlIGFsbG93ZWQKI2h0dHBfYWNjZXNzIGFsbG93IGxvY2FsbmV0CiNodHRwX2FjY2VzcyBhbGxvdyBsb2NhbGhvc3QKCiMgQW5kIGZpbmFsbHkgZGVueSBhbGwgb3RoZXIgYWNjZXNzIHRvIHRoaXMgcHJveHkKaHR0cF9hY2Nlc3MgYWxsb3cgYWxsCgojIFNxdWlkIG5vcm1hbGx5IGxpc3RlbnMgdG8gcG9ydCAzMTI4Cmh0dHBfcG9ydCA4MDgwIAoKIyBVbmNvbW1lbnQgYW5kIGFkanVzdCB0aGUgZm9sbG93aW5nIHRvIGFkZCBhIGRpc2sgY2FjaGUgZGlyZWN0b3J5LgpjYWNoZV9kaXIgdWZzIC9zcXVpZC92YXIvY2FjaGUvc3F1aWQgMTAwIDE2IDI1NgoKIyBMZWF2ZSBjb3JlZHVtcHMgaW4gdGhlIGZpcnN0IGNhY2hlIGRpcgpjb3JlZHVtcF9kaXIgL3NxdWlkL3Zhci9jYWNoZS9zcXVpZAoKIwojIEFkZCBhbnkgb2YgeW91ciBvd24gcmVmcmVzaF9wYXR0ZXJuIGVudHJpZXMgYWJvdmUgdGhlc2UuCiMKcmVmcmVzaF9wYXR0ZXJuIF5mdHA6CQkxNDQwCTIwJQkxMDA4MApyZWZyZXNoX3BhdHRlcm4gXmdvcGhlcjoJMTQ0MAkwJQkxNDQwCnJlZnJlc2hfcGF0dGVybiAtaSAoL2NnaS1iaW4vfFw/KSAwCTAlCTAKcmVmcmVzaF9wYXR0ZXJuIC4JCTAJMjAlCTQzMjAK
kind: Secret
metadata:
  creationTimestamp: null
  name: squid.conf

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: squid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squid
  template:
    metadata:
      labels:
        app: squid
    spec:
      containers:
      - image: jimmypw/squid
        name: squid

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: squid
  name: squid
spec:
  ports:
  - port: 3128
    protocol: TCP
    nodePort: 30005
  selector:
    app: squid
  type: NodePort
status:
  loadBalancer: {}


